#ifndef PLOT_ALGORITHM_H
#define PLOT_ALGORITHM_H

enum class SHOW_ALGORITHM { NORMAL = 0, MAX_NEG_95, NUM_660, PLAY_MPU6050 };
enum class CORRECTION_ALGORITHM { FITTING_KB = 0, FITTING_SIN };

#endif // PLOT_ALGORITHM_H
