#ifndef PLOT_ALGORITHM_H
#define PLOT_ALGORITHM_H

enum class SHOW_ALGORITHM {
    FREEDOM = 0,
    F15_CURVES,
    F15_SINGLE,
    PLAY_MPU6050,
    F30_CURVES,
    F30_SINGLE,
    LLC_CURVES,
};
enum class CORRECTION_ALGORITHM { FITTING_KB = 0, FITTING_SIN };

#endif // PLOT_ALGORITHM_H
